services:
  go_auth_postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - go_auth_postgres_data:/var/lib/postgresql/data

volumes:
  go_auth_postgres_data:
    name: go_auth_postgres_data
